spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always
